AWSTemplateFormatVersion: "2010-09-09"
Description: Ingest System for the outputs of the Analytics engine
Resources:
  IngestNewEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: new-event
      MessageRetentionPeriod: 86400
  IngestNewReservationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: new-reservation
      MessageRetentionPeriod: 86400


