AWSTemplateFormatVersion: "2010-09-09"
Description: Aggregator on ECS
Parameters:
  CodeVersion:
    Type: String
    Default: JVbpbepdr9haSzQLXAWfwa2BymH2psCd
Resources:
  AggClusterVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: "proj"
          Value: "mymovie"




  IAMIngestLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AggregatorLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Policies:
        - PolicyName: test-mymovie-GatewayLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchGetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource:
                  - arn:aws:dynamodb:eu-west-1:987471261617:table/test-mymovie-*
                Effect: Allow
  IngestNewEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: new-event
      MessageRetentionPeriod: 86400
  IngestNewReservationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: new-reservation
      MessageRetentionPeriod: 86400
  AggConfigQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: agg-config
      MessageRetentionPeriod: 86400



